### PR TITLE
Create scorecards.yml

### PR DESCRIPTION
**Pull request by aqualen**
This is a recommended tool to report on reputation/concerns with dependencies.

### CODE REVIEW

**Comment by aqualen** [comment]
Needs authentication perhaps (above my pay grade): https://github.com/ossf/scorecard-action#authentication

**Comment by jaycenhorton** [comment]
@aqualen added the workflow to master and bumped your commit

**Comment by jaycenhorton** [comment]
FYI AFAIK this only runs on master

**Comment by aqualen** [comment]
This really had little value for us.

**Pull request closed without merging**
